# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: octane-start-task@25
  inputs:
    OctaneServiceConnection: 'testAzure'
    WorkspaceList: '1002'
    CreatePipelineCheckbox: true

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: octane-end-task@25
  inputs:
    OctaneServiceConnection: 'testAzure'
    WorkspaceList: '1002'
